config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "todos#index"
  resources :users, :only => [:show, :index] do
  resources :todos
end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_todos, only: [:show, :edit, :update, :destroy,:index]

  def index
    
    if !current_user
    redirect_to user_session_path

  else
    
    @todos = @user.todos
  end
end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = params["user_id"]
     respond_to do |format|
    if @todo.save
     format.html {redirect_to :root}
     format.js { render :create}
    else
      render :root
      end
    end
  end
    

  def destroy
    @todo = Todo.find(params["id"])
    @todo.destroy
    respond_to do |format|
    format.html {redirect_to :root}
  end
end

def edit
  binding.pry
end

def update
  binding.pry
  @todo.notes=(params[:todo][:notes])
    respond_to do |format|
      if @todo.save
        format.html{redirect_to :root}
        format.js {render :edit}
      else
        render :root
      end
    end
end

private


  
def set_todos
  
@todo = @user.todos
end

def set_user
  
  @user = current_user
  
end

def todo_params
  params.require(:todo).permit(:notes, :user_id)
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  def show
 
    @user = current_user
    binding.pry
    @todos = @user.todos
  
  end

  def index
  if !current_user
    redirect_to user_session_path
  else
    @user = current_user
    @todos = @user.todos.where(user_id: current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoMvc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main-container" class="container">

  
  <div class="row">
       
        <div class="col-xs-3">
        <h3>Users link</h3>
        <ul class="nav">
        
        <li><%=link_to 'sign out', destroy_user_session_path,:method => :delete %></li>
        </ul>
        </div>
       
       <div class="col-xs-9">
       
      <%= yield %>
</div>
</div>
</div>

</html>

app/views/todos/_form.html.erb
<%= form_for([@user,Todo.new], remote: true) do |f| %>
  
  <%=f.label "new todo" %>
  <%=f.text_field :notes %>
  <%= submit_tag("ADD") %>
 <% end %>

app/views/todos/_todo.html.erb
<div class="row">
<%=div_for todo do %>
  
  <div class="col-xs-3">    
    <%=todo.notes%> | <%=todo.finished%> <%=link_to 'edit', edit_user_todo_path(@user,todo.id) %>
  </div>
  
  <div class="col-xs-3">
    <%=button_to 'Remove',user_todo_path(@user,todo.id), :method => :delete%>
  </div>
<%end%>
</div>

app/views/todos/create.html.erb
<%= form_for (@todo, url: todos_path) do |f| %>
  <%=f.text_field :notes %>
  <%=f.text_area :notes %>
  <%= submit_tag("ADD") %>
 <% end %>

app/views/todos/create.js.erb
$('#rd').append('<%= escape_javascript(render :partial => @todo)%>');
$('#todo_notes').val('');

app/views/todos/edit.html.erb
<%=render 'form' %>

app/views/todos/index.html.erb
<%=render 'form'%>

<div id="rd"><% @todo.each do |todo| %>
      <%=render :partial => @todo, todo: todo%>
  <%end%>

</div>
 


  

     

app/views/todos/new.html.erb
<%= form_for @todo, url: user_todos_path do |f| %>
  <%=f.label :notes %>
  <%=f.text_field :notes %>
  <%= submit_tag("ADD") %>
 <% end %>

<%@user.todos.each do |todo|%>
<ul>
<li><%=todo.notes%> <%=link_to 'delete todo',user_todo_path(@user,todo.id), :method => :delete%></li>
</ul>
<%end%>

<%=link_to 'make a new todo', new_user_todo_path(@user) %>

app/views/todos/show.html.erb
<h1>hi</h1>

app/views/todos/update.html.erb
<h1>coooool</h1>

app/views/users/_form.html.erb
<%= form_for Todo.new, url: user_todos_path(@user) , remote: true do |f| %>

  <%=f.label "new todo" %>
  <%=f.text_field :notes %>
  <%= submit_tag("ADD") %>
 <% end %>

app/views/users/_todo.html.erb
   <%=div_for todo do %>

   <div class="row colors">
   <div class="col-xs-3">
      <%=todo.notes%> 

</div>
<div class="col-xs-3">

  <%=todo.finished%> 
  <%=link_to 'edit', edit_user_todo_path(@user,todo.id) %>
</div>


<div class="col-xs-3">
  <%=button_to 'Remove',user_todo_path(@user,todo.id), :method => :delete%>
  </div>
</div>
  

  


<%end%>

app/views/users/index.html.erb
<%=render 'form'%>


<div id="rd">
<%=render :partial => @todo%>
</div>

app/views/users/show.html.erb
<%@user.todos.each do |todo|%>
<ul>
<li><%=todo.notes%> <%=link_to 'delete',user_todo_path(@user,todo.id), :method => :delete%></li>
</ul>
<%end%>

<%=link_to 'make a new todo', new_user_todo_path(@user) %>
  
  

  